---
apiVersion: v1
kind: Service
metadata:
  name: laundry-api
  namespace: mercury
  labels:
    app: laundry-api
spec:
  type: LoadBalancer
  selector:
    app: laundry-api
  ports:
    - port: 80
      targetPort: 8090
